### ISSUE TITLE
Flow API related todo list

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-combo-box#558]
### Value compatibility

Make sure all public-available user input elements follow these rules:

- [ ] the `value` property is declared as `String`
- [ ] the `value` property is not read-only and allows changes
- [ ] the `value` property declaration has `notify: true`

### Validation compatibility

Make sure all public-available validatable elements follow these rules:

- [ ] the `invalid` property is declared as `Boolean`
- [ ] the `invalid` property has `notify: true`
- [ ] `validate()` method updates the `invalid` state property

### `vaadin-combo-box-mixin.html`

- [ ] ❓ deprecate `open()` and `close()` methods for future removal in next major version, since duplicate of writable `opened` property
- [ ] ❓ deprecate `cancel()` method for future removal
  - probably duplicate of `comboBox.opened = false; comboBox.value = initialValue;`
- [ ] in `validate()` and `checkValidity()` methods, remove the `value` argument since not in use
- [ ] mark with `@private` and deprecate the `hasValue` property, only the argument should be kept for styling

### `vaadin-combo-box.html`

- [ ] remove the property `allowedPattern`, since not in use
- [ ] make sure the `pattern` property is used, add tests for it
- [ ] remove the property `inputmode`, since not in use
- [ ] remove the property `size`, since not in use

### `vaadin-combo-box-light.html`

- [ ] remove the property `overlayVerticalOffset`, since not in use in regular `<vaadin-combo-box>`
- [ ] ❓ deprecate `required` property, `validate()` and `checkValidity()` methods, since they alias to validation of the user’s provided input element
  - they should stay in regular `<vaadin-combo-box>`, however

### Mark with `@private` for the element classes

- `vaadin-combo-box-dropdown-wrapper.html`:
  - [ ] `class ComboBoxOverlayElement`
- `vaadin-combo-box-dropdown.html`:
  - [ ] `class VaadinComboBoxOverlay`
  - [ ] `class DropdownElement`
- `vaadin-combo-box-item.html`
  - [ ] `class ComboBoxItemElement`
